/* ============================================================
   pdf.js — "Export all to PDF".

   Zero-dependency: builds a clean printable document and uses the
   browser / OS print-to-PDF. Works on desktop (Save as PDF), Android
   Chrome, and the Capacitor WebView (Android print framework) — and
   stays consistent with the single-record print in detail.js.
   ============================================================ */
import { esc, fmtDateTime } from './ui.js';
import { TRAP_BY_KEY } from './content.js';

function moodLine(m) {
  const post = m.post != null ? m.post : m.pre;
  const moved = m.post != null && m.post !== m.pre ? ` → ${post}%` : '';
  return `${esc(m.name)} ${m.pre}%${moved}`;
}

function field(label, val) {
  return `<div class="pa-field"><b>${label}</b><span>${val ? esc(val) : '—'}</span></div>`;
}

function recordBlock(r, n) {
  const traps = (r.distortions || []).map((k) => (TRAP_BY_KEY[k] || {}).name || k).join(', ');
  const moods = (r.moods || []).map(moodLine).join('  ·  ') || '—';
  return `
    <section class="pa-rec">
      <div class="pa-rechead">
        <span>#${n}</span>
        <span>${esc(fmtDateTime(r.date))}${r.status === 'draft' ? ' · Draft' : ''}</span>
      </div>
      ${field('1 · Situation', r.situation)}
      <div class="pa-field"><b>2 · Moods</b><span>${moods}</span></div>
      ${field('3 · Thoughts', r.thoughts)}
      ${r.hotThought ? `<div class="pa-field"><b>Hot thought</b><span>“${esc(r.hotThought)}”</span></div>` : ''}
      ${traps ? `<div class="pa-field"><b>Thinking traps</b><span>${esc(traps)}</span></div>` : ''}
      ${field('4 · Evidence for', r.evidenceFor)}
      ${field('5 · Evidence against', r.evidenceAgainst)}
      <div class="pa-field"><b>6 · Balanced thought</b><span>${r.balancedThought ? esc(r.balancedThought) + ` (believe ${r.balancedBelief}%)` : '—'}</span></div>
      ${field('7 · Outcome', r.outcome)}
    </section>`;
}

/** Build a printable document of all records and open the print/PDF dialog.
 *  Returns false if there's nothing to export. */
export function exportAllPdf(records) {
  if (!records || !records.length) return false;

  // Clear any leftovers from a previous run.
  document.getElementById('print-all')?.remove();
  document.getElementById('pa-page-style')?.remove();

  const stamp = new Date().toLocaleDateString();
  const container = document.createElement('div');
  container.id = 'print-all';
  container.innerHTML = `
    <div class="pa-cover">
      <div class="pa-k">Cognitive Behavioural Therapy</div>
      <div class="pa-t">Reframe — Thought Records</div>
      <div class="pa-m">${records.length} record${records.length === 1 ? '' : 's'} · exported ${esc(stamp)}</div>
    </div>
    ${records.map((r, i) => recordBlock(r, i + 1)).join('')}
    <div class="pa-foot">Generated by Reframe · kept private on your device</div>`;

  // The single-record worksheet prints landscape; this multi-record doc
  // reads better in portrait, so override @page just for this run.
  const pageStyle = document.createElement('style');
  pageStyle.id = 'pa-page-style';
  pageStyle.textContent = '@media print { @page { size: A4 portrait; margin: 14mm; } }';

  document.head.appendChild(pageStyle);
  document.body.appendChild(container);
  document.body.classList.add('printing-all');

  const cleanup = () => {
    document.body.classList.remove('printing-all');
    container.remove();
    pageStyle.remove();
    window.removeEventListener('afterprint', cleanup);
  };
  window.addEventListener('afterprint', cleanup);
  setTimeout(() => { if (document.getElementById('print-all')) cleanup(); }, 60000); // safety net

  setTimeout(() => window.print(), 80); // let layout settle first
  return true;
}
